version: 2.1

executors:
  go-executor:
    working_directory: ~/url-shortener-go
    docker:
      - image: circleci/golang:1.16

commands:
  install-modules:
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Go module & linter download
          command: |
            go mod download
            go get -u golang.org/x/lint/golint

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  build-and-validate:
    executor: go-executor

    steps:
      - install-modules

      - run:
          name: Build and Validate
          command: go build

      - run:
          name: Start Application
          command: ./url-shortener-go
          background: true

      - run:
          name: Validate Application
          command: curl --retry 10 --retry-delay 1 -XPOST localhost:5000/ -d '{"long_url":"http://www.naver.com"}'

  check-linting:
    executor: go-executor

    steps:
      - install-modules

      - run:
          name: Check Linting
          command: |
            [[ -z $(go fmt) ]] && true || false
            go vet
            golint -set_exit_status

  run-test:
    executor: go-executor

    steps:
      - install-modules

      - run:
          name: Run tests and coverage
          command: go test -race -coverprofile=coverage.out -covermode=atomic

      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - build-and-validate
      - check-linting
      - run-test
