version: 2
jobs:
  build-and-validate:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Go module download
          command: go mod download

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Build Binary
          command: go build

      - run:
          name: Start Application
          command: ./url-shortener-go
          background: true

      - run:
          name: Validate Application
          command: curl --retry 10 --retry-delay 1 -XPOST localhost:5000/ -d '{"long_url":"http://www.naver.com"}'

  check-linting:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Go module download
          command: go mod download

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Golint
          command: golint -set_exit_status

workflows:
  version: 2
  main:
    jobs:
      - build-and-validate
      - check-linting
